from snakemake.utils import min_version

min_version("7.25.0")


localrules:
    all,
    curl__download_kraken_db,
    krona__update_taxonomy,
    custom__infer_and_store_read_group,


include: "rules/common.smk"
include: "rules/reads.smk"
include: "rules/mapping.smk"
include: "rules/kraken.smk"
include: "rules/consensus.smk"
include: "rules/nextclade.smk"


wildcard_constraints:
    **get_constraints(),


rule all:
    input:
        **get_fastqc_reports(),
        **get_bam_outputs(),
        **get_qualimap_reports(),
        **get_krona_reports(),
        **get_consensus_files(),
