### INPUT SECTION ###############################
reference_panel_dirpath: "/data/genome/virus/respiratory_panel/v2.2.0/" # Directory with viral fasta sequences. Take from https://github.com/xsitarcik/respiratory_panel.

reads: # Specify the order and methods for each read processing step. If no method is specified, the step will not be performed.
  subsampling: null # OPT - specify method of subsampling. Allowed: "seqtk", "null".
  trimming: "cutadapt" # OPT - specify method of trimming. Allowed: "cutadapt", "null".
  decontamination: "kraken" # OPT - specify method of decontamination. Allowed: "kraken", "null".
  deduplication: null # OPT - specify method of deduplication. Allowed: "fastuniq", "null".
  _generate_fastqc_for: ["original", "decontamination"] # OPT - specify which steps to generate fastqc for. Allowed: "original"."subsampling", "trimming", "decontamination", "deduplication" or empty list (default: empty list).

### HYPERPARAMETERS #############################

reads__trimming__cutadapt:
  # 1st stage - trimming
  cut_from_start_r1: null # OPT - removes a specified number of bases from the beginning of the R1 read.
  cut_from_start_r2: null # OPT - removes a specified number of bases from the beginning of the R2 read.
  cut_from_end_r1: null # OPT - removes a specified number of bases from the end of the R1 read.
  cut_from_end_r2: null # OPT - removes a specified number of bases from the end of the R2 read.
  quality_cutoff_from_5_end_r1: 20 # cutoff on 5' end of R1 read. The second step.
  quality_cutoff_from_3_end_r1: 20 # cutoff on 3' end of R1 read. The second step.
  quality_cutoff_from_5_end_r2: 20 # cutoff on 5' end of R2 read. The second step.
  quality_cutoff_from_3_end_r2: 20 # cutoff on 3' end of R2 read. The second step.

  # 2nd stage - Adapter removal
  adapter_removal: # OPT - set "do" to false to skip this step.
    do: false # If true, all below options are required. Else, they are ignored/can be deleted.

  # 3rd stage - post adapter trimming
  shorten_to_length: 500 # OPT - both R1 and R2 are shortened to this length.
  trim_N_bases_on_ends: null # OPT - trim flanking N's on both read ends.

  # 4th stage - Filtering
  min_length_r1: 35 # OPT - minimum R1 read length. If R1 read is shorter, both R1 and R2 reads are discarded. The fourth step.
  min_length_r2: 35 # OPT - minimum R2 read length. If R2 read is shorter, both R1 and R2 reads are discarded. The fourth step.
  max_length_r1: null # OPT - maximum R1 read length. If R1 read is longer, both R1 and R2 reads are discarded. The fourth step.
  max_length_r2: null # OPT - maximum R2 read length. If R2 read is longer, both R1 and R2 reads are discarded. The fourth step.
  max_n_bases: 3 # OPT - Discard read if R1 or R2 has more than the specified number of N bases. The fifth step.
  max_expected_errors: 3 # OPT - Discard read if R1 or R2 has more expected errors than this.

reads__decontamination__kraken:
  kraken_dir: "/data/genome/metagenome/kraken/k2_pluspf_20240112" # Directory containing kraken DB files. If does not exist, will be downloaded using the dirname.
  # get KRAKEN_TAG from https://benlangmead.github.io/aws-indexes/k2
  exclude_taxa_ids: # list of taxonomy IDs to exclude.
    - 9606 # Homo Sapiens
  exclude_children: false # Whether to exclude reads classified at more specific levels than specified taxonomy ID levels.
  exclude_ancestors: false # Whether to exclude reads classified at all taxonomy levels between root and the specified taxonomy ID levels.
  save_memory: true # If true, kraken limits RAM memory usage but sacrifices speed.
  generate_krona: true # If true, krona is generated from kraken report
  krona_dir: "/data/genome/taxonomy/krona/2023-12-03/" # Directory where krona dataset is located or will be downloaded.

consensus_params: # See Ivar consensus at https://andersen-lab.github.io/ivar/html/manualpage.html
  reference_criteria: # Here define criteria for references so they would be considered for further analysis.
    min_genome_fraction_with_10x_coverage: 10 # At least this percentage of genome must have coverage at least of 10x. Taken from samtools depth.

  count_orphans: false # Set to true to use also anomalous read pairs, i.e. without the properly-paired flag set.
  max_read_depth: 10000 # Limits the number of reads to load in memory per input file
  min_base_quality: 20 # Minimum base quality for a base to be considered. Setting to 0 make the overlapping bases reappear, albeit with 0 quality.
  min_mapping_quality: 20 # Minimum mapping quality for an alignment to be used.
  consensus_base_quality_threshold: 20 # Minimum quality score threshold to count base.
  consensus_frequency_threshold: 0.5 # Minimum frequency threshold to call consensus.
  min_consensus_depth: 10 # Minimum depth to call consensus.

mixed_positions_params: # See Ivar variants at https://andersen-lab.github.io/ivar/html/manualpage.html
  count_orphans: true # Set to true to use also anomalous read pairs, i.e. without the properly-paired flag set.
  max_read_depth: 10000 # Limits the number of reads to load in memory per input file.
  min_base_quality: 20 # Minimum base quality for a base to be considered. Setting to 0 make the overlapping bases reappear, albeit with 0 quality.
  min_mapping_quality: 20 # Minimum mapping quality for an alignment to be used.
  min_base_quality_threshold: 20 # Minimum quality score threshold to count base.
  min_frequency_threshold: 0.03 # Minimum frequency threshold (0 - 1) to call variants.
  min_read_depth: 10 # Minimum read depth to call variants.

  filtering: # Define filtering steps for the tsv result of ivar variants.
    min_alt_depth: 2 # Mixed positions must have at least this ALT_DP value.
    min_alt_freq: 0.1 # Mixed positions must have at least this ALT_FREQ value.
    max_alt_freq: 0.9 # Mixed positions cannot have ALT_FREQ value equal or larger than this.
    min_total_depth: 10 # Mixed positions must have at least this TOTAL_DP value.

# RESOURCES

max_threads: 8
max_mem_mb: 16384

resources:
  reads__trimming_mem_mb: 4096
  reads__fastqc_mem_mb: 2048
  mapping_mem_mb: 4096
  bam_index_mem_mb: 4096
  picard_mem_mb: 4096
  qualimap_mem_mb: 4096

threads:
  reads__trimming: 4
  reads__fastqc: 1
  reads__decontamination: 8
  mapping: 2
  bam_index: 2
