# INPUTS
sample_names_regex: ".*" # at results/reads/original
reference_panel_dirpath: "resources/test_reference_panel/" # directory with reference fasta sequences
references_metadata_file: "metadata.csv" # file in the reference panel directory with reference metadata

kraken_db: k2_viral_20230314 # Tag of kraken reference database. Get tag from https://benlangmead.github.io/aws-indexes/k2
kraken_dir: "resources/kraken" # Directory where kraken is located or will be downloaded

# PARAMETERS

reads__decontamination:
  exclude_taxa_ids: # list of taxonomy IDs to exclude
    - 9606 # Homo Sapiens
  exclude_children: false # whether to exclude reads classified at more specific levels than specified taxonomy ID levels
  exclude_ancestors: false # whether to exclude reads classified at all taxonomy levels between root and the specified taxonomy ID levels.

reads__trimming: # params are ignored if 'trimming' is not set in the main parameters
  shorten_to_length: 300 # OPT shorten to this length
  max_n_bases: 10 # OPT Discard reads with more than the specified number of bases. # fifth step
  max_expected_errors: 5 # OPT - discard reads with more expected errors than this.
  min_length_r1: 35 # OPT, # fourth step
  min_length_r2: 35 # OPT, # fourth step
  quality_cutoff_from_5_end_r1: 2 # OPT cutoff on 5' end of R1 read. The second step.
  quality_cutoff_from_3_end_r1: 2 # OPT cutoff on 3' end of R1 read. The second step.
  quality_cutoff_from_5_end_r2: 2 # OPT cutoff on 5' end of R2 read. The second step.
  quality_cutoff_from_3_end_r2: 2 # OPT cutoff on 3' end of R2 read. The second step.

consensus_params:
  reference_criteria: # Here define criteria for references so they would be considered for further analysis
    min_mean_coverage: 2 # Minimum mean coverage taken from qualimap

  count_orphans: false # Set to true to use also anomalous read pairs, i.e. without the properly-paired flag set.
  max_read_depth: 1000 # limits the number of reads to load in memory per input file
  min_base_quality: 13 # minimum base quality for a base to be considered. Setting to 0 make the overlapping bases reappear, albeit with 0 quality.
  min_mapping_quality: 0 # minimum mapping quality for an alignment to be used.
  consensus_base_quality_threshold: 20 # Minimum quality score threshold to count base.
  consensus_frequency_threshold: 0 # Minimum frequency threshold to call consensus.
  min_consensus_depth: 10 # Minimum depth to call consensus

mixed_positions_params:
  count_orphans: true # Set to true to use also anomalous read pairs, i.e. without the properly-paired flag set.
  max_read_depth: 600000 # limits the number of reads to load in memory per input file
  min_base_quality: 13 # minimum base quality for a base to be considered. Setting to 0 make the overlapping bases reappear, albeit with 0 quality.
  min_mapping_quality: 0 # minimum mapping quality for an alignment to be used.
  min_base_quality_threshold: 20 # Minimum quality score threshold to count base
  min_frequency_threshold: 0.03 # Minimum frequency threshold(0 - 1) to call variants
  min_read_depth: 0 # Minimum read depth to call variants

  filtering:
    min_alt_depth: 2 # mixed positions must have at least this ALT_DP value
    min_alt_freq: 0.1 # mixed positions must have at least this ALT_FREQ value
    max_alt_freq: 0.9 # mixed positions cannot have ALT_FREQ value equal or larger than this
    min_total_depth: 10 # mixed positions must have at least this TOTAL_DP value

# RESOURCES

max_threads: 2
max_mem_mb: 2048
