sample_names_regex: ".*"
reference_panel_dirpath: "resources/test_reference_panel/" # directory with reference fasta sequences
references_metadata_file: "metadata.csv" # file in the reference panel directory with reference metadata

threads: 2

kraken_db: k2_viral_20230314 # Tag of kraken reference database. Get tag from https://benlangmead.github.io/aws-indexes/k2

reads__decontamination:
  exclude_taxa_ids: # list of taxonomy IDs to exclude
    - 9606 # Homo Sapiens
  exclude_children: false # whether to exclude reads classified at more specific levels than specified taxonomy ID levels
  exclude_ancestors: false # whether to exclude reads classified at all taxonomy levels between root and the specified taxonomy ID levels.

reads__trimming: # Define one or more of the following trimmers
  quality_threshold: 20 # Minimal average quality of read bases to keep (inside sliding window of length 5)
  lead_trim: 0 # Remove leading low quality or N bases below this quality threshold
  trail_trim: 0 # Remove trailing low quality or N bases below this quality threshold
  crop_to_fixed_length: 300 # The number of bases to keep, from the start of the read
  head_crop: 0 # "Number of bases to remove from the start of read
  min_length_filter: 35 # Minimal length after trimming. Shorter reads would be removed
  illumina_clip: # Define to trim adapters, else remove from the config
    path_adapters: "resources/adapters/artic.fa" # Specifies the path to a fasta file containing all the adapters
    seed_mismatches: 2 # Specifies the maximum mismatch count which will still allow a full match to be performed
    palindrome_clip_threshold: 30 # Specifies how accurate the match between the two 'adapter ligated' reads must be for PE palindrome read alignment
    simple_clip_threshold: 10 # Specifies how accurate the match between any adapter etc. sequence must be against a read

consensus_params:
  reference_criteria:
    min_mean_coverage: 50

  count_orphans: false # Set to true to use also anomalous read pairs, i.e. without the properly-paired flag set.
  max_read_depth: 1000 # limits the number of reads to load in memory per input file
  min_base_quality: 13 # minimum base quality for a base to be considered. Setting to 0 make the overlapping bases reappear, albeit with 0 quality.
  min_mapping_quality: 0 # minimum mapping quality for an alignment to be used.
  consensus_base_quality_threshold: 20 # Minimum quality score threshold to count base.
  consensus_frequency_threshold: 0 # Minimum frequency threshold to call consensus.
  min_consensus_depth: 10 # Minimum depth to call consensus

mixed_positions_params:
  count_orphans: false # Set to true to use also anomalous read pairs, i.e. without the properly-paired flag set.
  max_read_depth: 600000 # limits the number of reads to load in memory per input file
  min_base_quality: 13 # minimum base quality for a base to be considered. Setting to 0 make the overlapping bases reappear, albeit with 0 quality.
  min_mapping_quality: 0 # minimum mapping quality for an alignment to be used.
  min_base_quality_threshold: 20 # Minimum quality score threshold to count base
  min_frequency_threshold: 0.03 # Minimum frequency threshold(0 - 1) to call variants
  min_read_depth: 0 # Minimum read depth to call variants

  filtering:
    min_alt_depth: 2 # mixed positions must have at least this ALT_DP value
    min_alt_freq: 0.1 # mixed positions must have at least this ALT_FREQ value
    max_alt_freq: 0.9 # mixed positions cannot have ALT_FREQ value equal or larger than this
    min_total_depth: 10 # mixed positions must have at least this TOTAL_DP value
