# INPUTS
pepfile: "config/pep/config.yaml" # here configure how to read the data
reference_panel_dirpath: "resources/test_reference_panel/" # directory with reference fasta sequences

reads: # Specify the order and methods for each read processing step. If no method is specified, the step will not be performed.
  subsampling: null # OPT - specify method of subsampling. Allowed: "seqtk", "null".
  trimming: "cutadapt" # OPT - specify method of trimming. Allowed: "cutadapt", "null".
  decontamination: "kraken" # OPT - specify method of decontamination. Allowed: "kraken", "null".
  deduplication: null # OPT - specify method of deduplication. Allowed: "fastuniq", "null".
  _generate_fastqc_for: ["decontamination"] # OPT - specify which steps to generate fastqc for. Allowed: "original"."subsampling", "trimming", "decontamination", "deduplication" or empty list (default: empty list).

# PARAMETERS

reads__trimming__cutadapt:
  cut_from_start_r1: null # null/int: Removes a specified number of bases from the beginning of the R1 read.
  cut_from_start_r2: null # null/int: Removes a specified number of bases from the beginning of the R2 read.
  cut_from_end_r1: null # null/int: Removes a specified number of bases from the end of the R1 read.
  cut_from_end_r2: null # null/int: Removes a specified number of bases from the end of the R2 read.
  quality_cutoff_from_3_end_r1: 2 # int(20): Removes lower quality bases from the 3' end of the R1 read.
  quality_cutoff_from_5_end_r1: 2 # int(20): Removes lower quality bases from the 5' end of the R1 read.
  quality_cutoff_from_3_end_r2: 2 # int(20): Removes lower quality bases from the 3' end of the R2 read.
  quality_cutoff_from_5_end_r2: 2 # int(20): Removes lower quality bases from the 5' end of the R2 read.
  nextseq_trimming_mode: false # bool(false): Modify quality-trimming algorithm to expect two-color chemistry data (NextSeq).
  do_adapter_removal: false # bool(false): Whether to do adapter removal or not.
  adapter_removal: # Relevant only if do_adapter_removal is set to true.
    action: "trim" # enum(trim): Defines an action to perform with the found adapter. Allowed: 'retain','trim','mask','none','lowercase'.
    overlap: 3 # int(3): Minimum number of bases required to overlap with the adapter.
    error_rate: 0.1 # float(0.1): Error tolerance used when searching for adapter.
    times: 1 # int(1): How many times to repeat adapter removal.
    keep_trimmed_only: false # bool(false): Discard reads with no adapters found.
    adapters_anywhere_file: "resources/adapters/artic_v4.fa"
    adapters_3_end_file: null # null/str: Fasta file path with adapters to be matched at 3'end.
    adapters_5_end_file: null # null/str: Fasta file path with adapters to be matched at 5'end.
  shorten_to_length: 500 # null/int: Shorten each read to the specified length. Corresponds to the cutadapt length parameter.
  trim_N_bases_on_ends: false # bool(false): Set to true to trim 'N' bases on ends.
  min_length_r1: 35 # null/int: Discards R1 reads shorter than this. Recommended to set at least to 1, to discard empty reads.
  min_length_r2: 35 # null/int: Discards R2 reads shorter than this. Recommended to set at least to 1, to discard empty reads.
  max_length_r1: null # null/int: Discards R1 reads longer than this value.
  max_length_r2: null # null/int: Discards R2 reads longer than this value.
  max_n_bases: null # null/int: Removes reads with more 'N' bases than the specified number.
  max_expected_errors: null # null/int: Discard reads whose expected number of errors exceeds this value.

reads__decontamination__kraken:
  kraken_dir: "references/kraken/k2_viral_20230605" # Directory containing kraken DB files. If does not exist, will be downloaded using the dirname
  exclude_taxa_ids: # list of taxonomy IDs to exclude
    - 9606 # Homo Sapiens
  exclude_children: false # whether to exclude reads classified at more specific levels than specified taxonomy ID levels
  exclude_ancestors: false # whether to exclude reads classified at all taxonomy levels between root and the specified taxonomy ID levels.
  save_memory: true # if true, kraken limits RAM memory usage but sacrifices speed
  generate_krona: false # bool(false): If true, krona is generated from kraken report.
  krona_dir: null # null/str: Directory where krona dataset is located, or where will be downloaded.

consensus_params:
  reference_criteria: # Here define criteria for references so they would be considered for further analysis
    min_genome_fraction_with_10x_coverage: 0.1 # At least this fraction of genome must have coverage at least of 10x.

  count_orphans: false # Set to true to use also anomalous read pairs, i.e. without the properly-paired flag set.
  max_read_depth: 1000 # limits the number of reads to load in memory per input file
  min_base_quality: 13 # minimum base quality for a base to be considered. Setting to 0 make the overlapping bases reappear, albeit with 0 quality.
  min_mapping_quality: 0 # minimum mapping quality for an alignment to be used.
  consensus_base_quality_threshold: 20 # Minimum quality score threshold to count base.
  consensus_frequency_threshold: 0 # Minimum frequency threshold to call consensus.
  min_consensus_depth: 10 # Minimum depth to call consensus

mixed_positions_params:
  count_orphans: true # Set to true to use also anomalous read pairs, i.e. without the properly-paired flag set.
  max_read_depth: 600000 # limits the number of reads to load in memory per input file
  min_base_quality: 13 # minimum base quality for a base to be considered. Setting to 0 make the overlapping bases reappear, albeit with 0 quality.
  min_mapping_quality: 0 # minimum mapping quality for an alignment to be used.
  min_base_quality_threshold: 20 # Minimum quality score threshold to count base
  min_frequency_threshold: 0.03 # Minimum frequency threshold(0 - 1) to call variants
  min_read_depth: 0 # Minimum read depth to call variants

  filtering:
    min_alt_depth: 2 # mixed positions must have at least this ALT_DP value
    min_alt_freq: 0.1 # mixed positions must have at least this ALT_FREQ value
    max_alt_freq: 0.9 # mixed positions cannot have ALT_FREQ value equal or larger than this
    min_total_depth: 10 # mixed positions must have at least this TOTAL_DP value

# RESOURCES

max_threads: 2
max_mem_mb: 2048

resources:
  reads__trimming_mem_mb: 4096
  reads__fastqc_mem_mb: 2048
  mapping_mem_mb: 4096
  bam_index_mem_mb: 4096
  picard_mem_mb: 4096
  qualimap_mem_mb: 4096

threads:
  reads__trimming: 2
  reads__fastqc: 2
  reads__decontamination: 2
  mapping: 2
  bam_index: 2
