"$schema": http://json-schema.org/draft-06/schema#
"$ref": "#/definitions/Respiratory"
definitions:
  Respiratory:
    type: object
    additionalProperties: true
    properties:
      pepfile:
        type: string
        description: "Path to the PEP file containing the info how to load the data"
        default: "config/pep/config.yaml"
      reference_panel_dirpath:
        type: string
        description: "Directory with reference .fasta files"
      max_threads:
        type: integer
        description: "Number of maximum threads to use in jobs"
        default: 1
        minimum: 1
      max_mem_mb:
        type: integer
        description: "Maximum memory in megabytes to allocate for any job"
        minimum: 2048
        default: 2048
      consensus_params:
        type: object
        "$ref": "#/definitions/ConsensusParams"
      mixed_positions_params:
        type: object
        "$ref": "#/definitions/MixedPositionsParams"
      resources:
        type: object
        "$ref": "#/definitions/Resources"
      threads:
        type: object
        "$ref": "#/definitions/Threads"
    required:
      - pepfile
      - reference_panel_dirpath
      - threads
      - consensus_params
      - mixed_positions_params
      - resources
    title: Respiratory
  ConsensusParams:
    type: object
    additionalProperties: false
    properties:
      reference_criteria:
        type: object
        "$ref": "#/definitions/ReferenceCriteria"
      count_orphans:
        type: boolean
        default: false
        description: "Set to true to use also anomalous read pairs, i.e. without the properly-paired flag set."
      max_read_depth:
        type: integer
        default: 1000
        description: "This limits the number of reads to load in memory per input file. Decreases needed memory but increases running time."
      min_base_quality:
        type: integer
        default: 13
        description: "Minimum base quality for a base to be considered. Setting to 0 make the overlapping bases reappear, albeit with 0 quality."
      min_mapping_quality:
        type: integer
        default: 0
        description: "Minimum mapping quality for an alignment to be used."
      consensus_base_quality_threshold:
        type: integer
        default: 20
        description: "Minimum quality score threshold to count base in ivar consensus"
      consensus_frequency_threshold:
        type: number
        default: 0
        minimum: 0
        maximum: 1
        description: "Minimum frequency threshold to call consensus."
      min_consensus_depth:
        type: integer
        default: 10
        description: "Minimum depth to call consensus"
    required:
      - reference_criteria
    title: ConsensusParams
  ReferenceCriteria:
    type: object
    additionalProperties: false
    properties:
      min_genome_fraction_with_10x_coverage:
        type: number
        description: "At least this fraction of genome must have coverage at least of 10x so the sample would be marked as mapped to the reference. Taken from Qualimap."
        default: 10
    required:
      - min_genome_fraction_with_10x_coverage
    title: ReferenceCriteria
  MixedPositionsParams:
    type: object
    additionalProperties: false
    properties:
      count_orphans:
        type: boolean
        default: false
        description: "Set to true to use also anomalous read pairs, i.e. without the properly-paired flag set."
      max_read_depth:
        type: integer
        default: 600000
        description: "This limits the number of reads to load in memory per input file. Decreases needed memory but increases running time."
      min_base_quality:
        type: integer
        default: 13
        description: "Minimum base quality for a base to be considered. Setting to 0 make the overlapping bases reappear, albeit with 0 quality."
      min_mapping_quality:
        type: integer
        default: 0
        description: "Minimum mapping quality for an alignment to be used."
      min_base_quality_threshold:
        type: integer
        default: 20
        description: "Minimum quality score threshold to count base in ivar variants"
      min_frequency_threshold:
        type: number
        default: 0
        minimum: 0
        maximum: 1
        description: "Minimum frequency threshold to call variants."
      min_read_depth:
        type: integer
        default: 10
        description: "Minimum read depth to call variants"
      filtering:
        type: object
        "$ref": "#/definitions/MixedPositionsCriteria"
    title: MixedPositionsParams
  MixedPositionsCriteria:
    type: object
    additionalProperties: false
    properties:
      min_alt_depth:
        type: integer
        default: 2
        description: "Mixed positions must have at least this ALT_DP value to be counted"
      min_alt_freq:
        type: number
        default: 0.1
        description: "Mixed positions must have at least this ALT_FREQ value to be counted"
      max_alt_freq:
        type: number
        default: 0.9
        description: "Mixed positions cannot have ALT_FREQ equal or greater than this value"
      min_total_depth:
        type: integer
        default: 10
        description: "Mixed positions must have at least this TOTAL_DP value to be counted"
    title: MixedPositionsCriteria
  Resources:
    mapping_mem_mb:
      type: integer
      description: "Memory in MB to reserve for mapping"
    bam_index_mem_mb:
      type: integer
      description: "Memory in MB to reserve for bam_index"
    picard_mem_mb:
      type: integer
      description: "Memory in MB to reserve for picard"
    qualimap_mem_mb:
      type: integer
      description: "Memory in MB to reserve for qualimap"
    title: Resources
  Threads:
    mapping:
      type: integer
      default: 1
      description: "Number of threads to use for mapping"
    bam_index:
      type: integer
      default: 1
      description: "Number of threads to use for bam_index"
    title: Threads
