"$schema": http://json-schema.org/draft-06/schema#
"$ref": "#/definitions/Respiratory"
definitions:
  Respiratory:
    type: object
    additionalProperties: false
    properties:
      sample_names_regex:
        type: string
      reference_panel_dirpath:
        type: string
      threads:
        type: integer
        description: "Number of threads"
        Minimum: 1
      kraken_db:
        type: string
        description: "Tag for the kraken database which will be used"
      reads__trimming:
        type: object
        "$ref": "#/definitions/ReadsTrimming"
      reads__decontamination:
        type: object
        "$ref": "#/definitions/ReadsDecontamination"
      consensus_params:
        type: object
        "$ref": "#/definitions/ConsensusParams"
      mixed_positions_params:
        type: object
        "$ref": "#/definitions/MixedPositionsParams"
    required:
      - sample_names_regex
      - reference_panel_dirpath
      - threads
      - kraken_db
      - consensus_params
      - mixed_positions_params
    title: Respiratory
  ReadsDecontamination:
    type: object
    additionalProperties: false
    properties:
      exclude_taxa_ids:
        type: array
        description: "list of taxonomy IDs to exclude"
        items:
          type: integer
      exclude_children:
        type: boolean
        default: false
        description: "whether to exclude reads classified at more specific levels than specified taxonomy ID levels"
      exclude_ancestors:
        type: boolean
        default: false
        description: "whether to exclude reads classified at all taxonomy levels between root and the specified taxonomy ID levels"
    required:
      - exclude_taxa_ids
  ReadsTrimming:
    type: object
    additionalProperties: false
    properties:
      quality_threshold:
        type: integer
        description: "Minimal average quality of read bases to keep (inside sliding window of length 5)"
      lead_trim:
        type: integer
        description: "Remove leading low quality or N bases below this quality threshold"
      trail_trim:
        type: integer
        description: "Remove trailing low quality or N bases below this quality threshold"
      crop_to_fixed_length:
        type: integer
        description: "The number of bases to keep, from the start of the read."
      head_crop:
        type: integer
        description: "Number of bases to remove from the start of read"
      min_length_filter:
        type: integer
        description: "Minimal length after trimming. Shorter reads would be removed."
      illumina_clip:
        type: object
        "$ref": "#/definitions/IlluminaClipping"
    title: ReadsTrimming
  IlluminaClipping:
    type: object
    additionalProperties: false
    properties:
      path_adapters:
        type: string
        description: "Specifies the path to a fasta file containing all the adapters"
      seed_mismatches:
        type: integer
        description: "Specifies the maximum mismatch count which will still allow a full match to be performed"
      palindrome_clip_threshold:
        type: integer
        description: "Specifies how accurate the match between the two 'adapter ligated' reads must be for PE palindrome read alignment."
      simple_clip_threshold:
        type: integer
        description: "Specifies how accurate the match between any adapter etc. sequence must be against a read."
    required:
      - path_adapters
      - seed_mismatches
      - palindrome_clip_threshold
      - simple_clip_threshold
    title: IlluminaClipping
  ConsensusParams:
    type: object
    additionalProperties: false
    properties:
      reference_criteria:
        type: object
        "$ref": "#/definitions/ReferenceCriteria"
      count_orphans:
        type: boolean
        default: false
        description: "Set to true to use also anomalous read pairs, i.e. without the properly-paired flag set."
      max_read_depth:
        type: integer
        default: 1000
        description: "This limits the number of reads to load in memory per input file. Decreases needed memory but increases running time."
      min_base_quality:
        type: integer
        default: 13
        description: "Minimum base quality for a base to be considered. Setting to 0 make the overlapping bases reappear, albeit with 0 quality."
      min_mapping_quality:
        type: integer
        default: 0
        description: "Minimum mapping quality for an alignment to be used."
      consensus_base_quality_threshold:
        type: integer
        default: 20
        description: "Minimum quality score threshold to count base in ivar consensus"
      consensus_frequency_threshold:
        type: integer
        default: 0
        Minimum: 0
        Maximum: 1
        description: "Minimum frequency threshold to call consensus."
      min_consensus_depth:
        type: integer
        default: 10
        description: "Minimum depth to call consensus"
    required:
      - reference_criteria
    title: ConsensusParams
  ReferenceCriteria:
    type: object
    additionalProperties: false
    properties:
      min_mean_coverage:
        type: integer
        description: "Minimum mean coverage so the sample would be marked as mapped to the reference"
    required:
      - min_mean_coverage
    title: ReferenceCriteria

  MixedPositionsParams:
    type: object
    additionalProperties: false
    properties:
      count_orphans:
        type: boolean
        default: false
        description: "Set to true to use also anomalous read pairs, i.e. without the properly-paired flag set."
      max_read_depth:
        type: integer
        default: 600000
        description: "This limits the number of reads to load in memory per input file. Decreases needed memory but increases running time."
      min_base_quality:
        type: integer
        default: 13
        description: "Minimum base quality for a base to be considered. Setting to 0 make the overlapping bases reappear, albeit with 0 quality."
      min_mapping_quality:
        type: integer
        default: 0
        description: "Minimum mapping quality for an alignment to be used."
      min_base_quality_threshold:
        type: integer
        default: 20
        description: "Minimum quality score threshold to count base in ivar variants"
      min_frequency_threshold:
        type: number
        default: 0
        Minimum: 0
        Maximum: 1
        description: "Minimum frequency threshold to call variants."
      min_read_depth:
        type: integer
        default: 10
        description: "Minimum read depth to call variants"
      filtering:
        type: object
        "$ref": "#/definitions/MixedPositionsCriteria"
    title: MixedPositionsParams
  MixedPositionsCriteria:
    type: object
    additionalProperties: false
    properties:
      min_alt_depth:
        type: integer
        default: 2
        description: "Mixed positions must have at least this ALT_DP value to be counted"
      min_alt_freq:
        type: number
        default: 0.1
        description: "Mixed positions must have at least this ALT_FREQ value to be counted"
      max_alt_freq:
        type: number
        default: 0.9
        description: "Mixed positions cannot have ALT_FREQ equal or greater than this value"
      min_total_depth:
        type: integer
        default: 10
        description: "Mixed positions must have at least this TOTAL_DP value to be counted"
    title: MixedPositionsCriteria
